# Setup
title: Teaching Computational Geometry and Topology
tagline: A resource for teachers (and students) of computational geometry and topology.
baseurl: "/teaching-compGT"
paginate: 1
locale: "en"

# About/contact
author1:
  name: David L. Millman
  url: http://millman.us
  email: david.millman@montana.edu
author2:
  name: Joe Mitchell
  url: http://www.ams.sunysb.edu/~jsbm/

# Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
